# Generated by Django 2.2.3 on 2019-07-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_du_vol', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(blank=True, default='', max_length=50)),
                ('case', models.CharField(blank=True, default='', max_length=100)),
                ('statut', models.CharField(choices=[('disponible', 'DISPONIBLE'), ('En cours de traitement', 'EN COURS DE TRAITMENT'), ('Prévu', 'PREVU')], default='Prévu', max_length=100)),
                ('capteurs', models.CharField(choices=[('Thermique', 'THERMIQUE'), ('Optique', 'OPTIQUE'), ('Météo', 'METEO')], default='Optique', max_length=100)),
            ],
            options={
                'ordering': ('date_du_vol',),
            },
        ),
    ]
