# Generated by Django 2.2.3 on 2019-07-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('image', models.ImageField(upload_to='midgard/static/img/profiles')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_du_vol', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='midgard/static/img')),
                ('nome', models.CharField(blank=True, default='', max_length=50)),
                ('case', models.CharField(blank=True, default='', max_length=100)),
                ('statut', models.CharField(choices=[('disponible', 'DISPONIBLE'), ('En cours de traitement', 'EN COURS DE TRAITMENT'), ('Prévu', 'PREVU')], default='Prévu', max_length=100)),
                ('capteurs', models.CharField(choices=[('Thermique', 'THERMIQUE'), ('Optique', 'OPTIQUE'), ('Météo', 'METEO')], default='Optique', max_length=100)),
            ],
            options={
                'ordering': ('date_du_vol',),
            },
        ),
    ]
