# Generated by Django 2.2.3 on 2019-07-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vols',
            name='vol',
            field=models.ImageField(default=2, upload_to=None),
            preserve_default=False,
        ),
    ]
