# Generated by Django 2.2.3 on 2019-07-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midgard', '0002_auto_20190715_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='vols',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vols', to='midgard.Profiles'),
            preserve_default=False,
        ),
    ]
