# Generated by Django 2.2.3 on 2019-07-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgard', '0002_vols_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vols',
            name='vol',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
