# Generated by Django 2.2.3 on 2019-07-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgard', '0003_auto_20190712_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vols',
            name='vol',
            field=models.ImageField(upload_to='midgard/static/img'),
        ),
    ]
