# Generated by Django 2.2.3 on 2019-07-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgard', '0003_vols_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='username',
        ),
        migrations.AddField(
            model_name='profiles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
