# Generated by Django 2.2.3 on 2019-07-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgard', '0004_auto_20190715_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
